export const parsedProjects = [
    { id: 1, img: "/Images2nd/78th Independence day.jpg", category: "Production", title: "78th Independence day", gridX: "2%", gridY: "0vh", width: "16vw" },
    { id: 2, img: "/Images2nd/ACE.jpg", category: "Production", title: "ACE", gridX: "22%", gridY: "20vh", width: "16vw" },
    { id: 3, img: "/Images2nd/Adipurush.jpg", category: "VFX", title: "Adipurush", gridX: "42%", gridY: "40vh", width: "16vw" },
    { id: 4, img: "/Images2nd/Beauty_Pagent.jpg", category: "Events", title: "Beauty Pagent", gridX: "62%", gridY: "10vh", width: "16vw" },
    { id: 5, img: "/Images2nd/Conistable.jpg", category: "Production", title: "Conistable", gridX: "82%", gridY: "30vh", width: "16vw" },
    { id: 6, img: "/Images2nd/Custody .jpg", category: "Production", title: "Custody ", gridX: "2%", gridY: "60vh", width: "16vw" },
    { id: 7, img: "/Images2nd/Ela.jpg", category: "Production", title: "Ela", gridX: "22%", gridY: "80vh", width: "16vw" },
    { id: 8, img: "/Images2nd/Gandharwa.jpg", category: "Production", title: "Gandharwa", gridX: "42%", gridY: "100vh", width: "16vw" },
    { id: 9, img: "/Images2nd/Gowtham.jpg", category: "Production", title: "Gowtham", gridX: "62%", gridY: "70vh", width: "16vw" },
    { id: 10, img: "/Images2nd/Hayaa.jpg", category: "Production", title: "Hayaa", gridX: "82%", gridY: "90vh", width: "16vw" },
    { id: 11, img: "/Images2nd/Holi Masti.jpg", category: "Events", title: "Holi Masti", gridX: "2%", gridY: "120vh", width: "16vw" },
    { id: 12, img: "/Images2nd/Iravatam.jpg", category: "Production", title: "Iravatam", gridX: "22%", gridY: "140vh", width: "16vw" },
    { id: 13, img: "/Images2nd/Mahanadu.jpg", category: "Events", title: "Mahanadu", gridX: "42%", gridY: "160vh", width: "16vw" },
    { id: 14, img: "/Images2nd/Meter.jpg", category: "Production", title: "Meter", gridX: "62%", gridY: "130vh", width: "16vw" },
    { id: 15, img: "/Images2nd/Mothevari Love story.jpg", category: "Production", title: "Mothevari Love story", gridX: "82%", gridY: "150vh", width: "16vw" },
    { id: 16, img: "/Images2nd/NTR100.jpg", category: "Production", title: "NTR100", gridX: "2%", gridY: "180vh", width: "16vw" },
    { id: 17, img: "/Images2nd/Neon_Monkey_Fest_1_Main_Poster.jpg", category: "Events", title: "Neon Monkey Fest 1 Main Poster", gridX: "22%", gridY: "200vh", width: "16vw" },
    { id: 18, img: "/Images2nd/Neon_Monkey_Fest_2.jpg", category: "Events", title: "Neon Monkey Fest 2", gridX: "42%", gridY: "220vh", width: "16vw" },
    { id: 19, img: "/Images2nd/Neon_Monkey_Fest_3.jpg", category: "Events", title: "Neon Monkey Fest 3", gridX: "62%", gridY: "190vh", width: "16vw" },
    { id: 20, img: "/Images2nd/Noel's Telugodi Beat.jpg", category: "Production", title: "Noel's Telugodi Beat", gridX: "82%", gridY: "210vh", width: "16vw" },
    { id: 21, img: "/Images2nd/Nuvve_kaavali.jpg", category: "Production", title: "Nuvve kaavali", gridX: "2%", gridY: "240vh", width: "16vw" },
    { id: 22, img: "/Images2nd/Phalana abbai phalana ammai.jpg", category: "Production", title: "Phalana abbai phalana ammai", gridX: "22%", gridY: "260vh", width: "16vw" },
    { id: 23, img: "/Images2nd/Police vari hecharika.jpg", category: "Production", title: "Police vari hecharika", gridX: "42%", gridY: "280vh", width: "16vw" },
    { id: 24, img: "/Images2nd/Ramabanam.jpg", category: "Production", title: "Ramabanam", gridX: "62%", gridY: "250vh", width: "16vw" },
    { id: 25, img: "/Images2nd/Ravana_Dahanam.jpg", category: "Production", title: "Ravana Dahanam", gridX: "82%", gridY: "270vh", width: "16vw" },
    { id: 26, img: "/Images2nd/Vihaari.jpg", category: "Production", title: "Vihaari", gridX: "2%", gridY: "300vh", width: "16vw" },
    { id: 27, img: "/Images2nd/Vihari_Song.jpg", category: "Production", title: "Vihari Song", gridX: "22%", gridY: "320vh", width: "16vw" },
    { id: 28, img: "/Images2nd/simhadri-kannada-et00024656-1673613476.avif", category: "Production", title: "simhadri kannada et00024656 1673613476", gridX: "42%", gridY: "340vh", width: "16vw" }
];
